/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": {
          DEFAULT: '#135bec',
          50: '#eef3fe',
          100: '#dae7fd',
          200: '#bccffb',
          300: '#8fadfa',
          400: '#5c82f6',
          500: '#135bec',
          600: '#0e46c4',
          700: '#0b379e',
          800: '#0a2e82',
          900: '#082669',
        },
        "background-light": "#f6f6f8",
        "background-dark": "#101622",
        "brand": {
          "DEFAULT": "#135bec",
          "dark": "#0e46b6",
          "light": "#e7effd",
        },
        "security": {
          "high": "#0f172a",
        },
        "on-surface-variant": "#475569",
        "inverse-on-surface": "#f1f5f9",
        "on-error": "#ffffff",
        "error": "#ef4444",
        "on-tertiary-fixed": "#020617",
        "tertiary": "#0f172a",
        "inverse-surface": "#1e293b",
        "on-secondary-container": "#1e293b",
        "secondary": "#475569",
        "on-primary": "#ffffff",
        "outline-variant": "#e2e8f0",
        "surface-variant": "#f1f5f9",
        "secondary-container": "#f1f5f9",
        "surface": "#ffffff",
        "on-primary-fixed": "#1e3a8a",
        "on-tertiary": "#ffffff",
        "on-error-container": "#991b1b",
        "tertiary-fixed": "#f8fafc",
        "tertiary-container": "#334155",
        "primary-fixed": "#dbeafe",
        "on-secondary-fixed": "#0f172a",
        "secondary-fixed-dim": "#e2e8f0",
        "secondary-fixed": "#f1f5f9",
        "outline": "#cbd5e1",
        "on-background": "#0f172a",
        "surface-container-highest": "#e1e4f0",
        "surface-dim": "#f6f6f8",
        "on-primary-container": "#1e40af",
        "on-primary-fixed-variant": "#1d4ed8",
        "on-tertiary-fixed-variant": "#1e293b",
        "on-secondary-fixed-variant": "#334155",
        "surface-tint": "#135bec",
        "background": "#f6f6f8",
        "on-surface": "#0f172a",
        "tertiary-fixed-dim": "#f1f5f9",
        "inverse-primary": "#93c5fd",
        "surface-container-low": "#f8f9fc",
        "on-secondary": "#ffffff",
        "surface-bright": "#ffffff",
        "primary-container": "#dbeafe",
        "on-tertiary-container": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8ebf4",
        "surface-container": "#f1f3f9",
        "primary-fixed-dim": "#bfdbfe",
        "error-container": "#fee2e2"
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "custom": "8px",
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
